### ISSUE TITLE
Where to put description of project?

### ISSUE THREAD

**Issue by ProfTina** [yale-web-technologies/mirador#10]
I have a student writing an explanation of the editions. I know that this is LOW priority--but where could we put the splash pages for each of the projects (and not just 10kr in general)?

**Comment by gigamorph** [comment]
Although we don't know yet exactly how each room will be implemented exactly, it has become high priority that we need to have "something" to distinguish each room. By the end of next week it will probably show some basic stuff (e.g. title + description) for each "room", but you shouldn't expect it to be perfectly styled.

**Comment by gigamorph** [comment]
Since we now have different rooms, showing the description per project is technically possible, but it will have to be a single chunk of plain or html text and you will have to send it to me to update the page.

**Comment by gigamorph** [comment]
Again, I can put up basic text for each project if you send it to me. Otherwise we should discuss it as part of the requirements of the "portal" when we begin working on it. Closing the ticket for now.
