### ISSUE TITLE
zengping butu

### ISSUE THREAD

**Issue by ProfTina** [yale-web-technologies/mirador#12]
Dear Lec and Team,
1. Do you know when you will be able to post the TIFF version of this text?  It's still the PDF version.
2. Can we somehow leave up a sample text somewhere where we allow people to tinker with the annotation functions before they actually start work on some images?  I think that kind of demo would be very useful.  
Thanks,
Tina

**Comment by gigamorph** [comment]
Hi Tina,

Regarding (1), you are talking about "增評補圖石頭記 (1988 中国书店/光緒十年1884) edition" that Nick uploaded to the google drive, right? Neil, our staff member that will install the images, is out until Thursday, so unfortunately it won't be ready until this Friday, if not later.

(2), we are working on setting up a "staging" server that is mostly meant for testing new functionalities before release. We will let you know as soon as it is available.

**Comment by gigamorph** [comment]
(1) Actually those images seem to be ready. I'll put them together soon, Wednesday at the latest.

-Seong

**Comment by ProfTina** [comment]
Great!  That's wonderful.

On Mon, Apr 11, 2016 at 10:02 PM, Seong-June Kim notifications@github.com
wrote:

> (1) Actually those images seem to be ready. I'll put them together soon,
> Wednesday at the latest.
> 
> -Seong
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/yale-web-technologies/mirador/issues/12#issuecomment-208662966

## 

Tina Lu
Professor of Chinese Literature
Dept. of East Asian Languages and Literatures
Yale University
P.O. Box 208236
New Haven, CT 06520-8236

**Comment by gigamorph** [comment]
(1) Images have been added. Set the title to 增評補圖石頭記. I'm still working on dividing up chapters.

**Comment by gigamorph** [comment]
I think the questions have been answered above. Closing.
