### ISSUE TITLE
cannot open any windows

### ISSUE THREAD

**Issue by ProfTina** [yale-web-technologies/mirador#14]
I am looking at the TIFFs for Zengping butu, but I cannot add any annotations at all.  Is something the matter right now?  

Also!  Is there any chance that the images can be corrected and made to stand straighter?

Thanks,
Tina

**Comment by gigamorph** [comment]
Experimenting with chapters had broken the existing code. I'll file the bug with IIIF/mirador. It should work now, since I have replaced the manifest. 

Regarding the tilted images, there's not much I can do about it. They will have to be re-scanned (by Nick?).
