### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by ProfTina** [yale-web-technologies/mirador#6]
This may not be the right place to add this!  But now that there is content we need to add some layer of password protection ASAP.  Thanks, Tina

**Comment by gigamorph** [comment]
It's the perfect place. We are working on it but it will take some time. As a temporary measure we can add CAS immediately, but then people from outside the university won't be able to access the site. Would it something you would be fine with? Maybe we can talk about this in the meeting.

**Comment by ProfTina** [comment]
Let me talk about this with Mick at the office, ok?

**Comment by ProfTina** [comment]
OK--so Mick and I both feel the answer depends on how long it would take to get real password protection up.  
Let's make this a topic at our meeting.

**Comment by gigamorph** [comment]
CAS has been enabled for the front end. It doesn't yet protect us from malicious attackers.

**Comment by gigamorph** [comment]
Done.
